-- ==========================================================================
-- d1_oefening_7 - SQL schrijven met een LLM: laten schrijven, zelf controleren
-- ==========================================================================
--
-- Werkwijze (tweetallen):
--     1. Bedenk samen:
--           - hoeveel rijen verwacht je?
--           - één bedrijf waarvan je het antwoord kunt narekenen
--           - welke join kan rijen vermenigvuldigen?
--     2. Vul het prompt-sjabloon hieronder aan en stuur het naar een LLM (ChatGPT, Claude, Copilot, ...).
--     3. Plak de query van het LLM hieronder, draai hem, draai je checks. Klopt het?
--     4. Niet? Fix het zelf (of laat het model fixen, maar snap de fix).
--     Geen LLM bij de hand? Persoon A schrijft de query zelf; persoon B speelt reviewer.
--
-- Vraag A: geef per bedrijf (CompanyName) het aantal orders en de totale orderwaarde (TotalDue).
--          1 rij per bedrijf. Sorteer op orderwaarde aflopend.
--
-- Vraag B: welke bedrijven hebben een product van productmodel 'Racing Socks' besteld? 1 rij per bedrijf.
--
-- ---------------------------------------------------------------------------
-- PROMPT-SJABLOON (kopieer, vul de vraag in)
-- ---------------------------------------------------------------------------
-- Je bent een data-analist. Dialect: DuckDB (Postgres-achtig: LIMIT, COALESCE, length, date_diff;
-- géén TOP, ISNULL, GETDATE of [haken]).
--
-- Schema (PK = primary key, FK = foreign key):
--   SalesLT.Customer(CustomerID PK, CompanyName, FirstName, LastName, EmailAddress)
--   SalesLT.SalesOrderHeader(SalesOrderID PK, CustomerID FK->Customer, OrderDate, SubTotal, TaxAmt, Freight, TotalDue)
--   SalesLT.SalesOrderDetail(SalesOrderDetailID PK, SalesOrderID FK->SalesOrderHeader, ProductID FK->Product,
--                            OrderQty, UnitPrice, UnitPriceDiscount, LineTotal)
--   SalesLT.Product(ProductID PK, Name, ProductModelID FK->ProductModel, ListPrice, StandardCost)
--   SalesLT.ProductModel(ProductModelID PK, Name)
--
-- Vraag: [VRAAG A of B].
-- Stijl: keywords in hoofdletters, komma's vóór de kolomnaam, elke clause op een nieuwe regel,
-- aliases voor tabellen en berekende kolommen, WHERE 1=1 gevolgd door AND-filters.
-- Noem je aannames expliciet. Geef daarna een aparte controle-query voor het aantal rijen of het totaal.
-- ---------------------------------------------------------------------------

-- Query van het LLM:


-- Eigen checks (schrijf ze op VOORDAT je het antwoord ziet):
-- check 1: verwacht aantal rijen
-- check 2: één bedrijf narekenen
-- check 3: fan-out-test (rijen tellen vóór en ná de join)
